### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by richardrl** [mctorch/mctorch#18]
```
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/richard/improbable/mctorch/torch/__init__.py", line 23, in <module>
    from .version import __version__
ModuleNotFoundError: No module named 'torch.version'

```
Hi, I got this error when following the instructions for pytorch installation on Ubuntu.

I skipped this line because I already had pytorch installed...

`conda install -c pytorch magma-cuda90 # or [magma-cuda80 | magma-cuda92 | magma-cuda100 ] depending on your cuda version
`

**Comment by bamdevm** [comment]
Oh, can you try installing afresh ie don't skip that line. Currently McTorch is tightly tied to a specific version of Pytorch.

**Comment by bamdevm** [comment]
You might already be aware of it. We overload few functionalities of Pytorch in McTorch for easy compatibility.
Let us know your experience.

**Comment by richardrl** [comment]
Will it work with pip ? Most of my other packages are in pip.

**Comment by richardrl** [comment]
Also, what is this command doing for mctorch? It seems to be very slow - using 100% of all 8 CPUs of my computer and taking 30 minutes.

`  Running command git submodule update --init --recursive -q
`

**Comment by bamdevm** [comment]
Not totally sure. We will come back. 

Did you look at the installation FAQs section in our readme file?

**Comment by bamdevm** [comment]
@richardrl, did it work?

**Comment by richardrl** [comment]
@bamdevm Hi yes, if I follow the instructions exactly it works, but:

`  Running command git submodule update --init --recursive -q
`

This step to install takes 30 minutes, very slow

Also curious about how to get it working in pip. It seems like your installation procedure requires anaconda somewhere, because "pip install pytorch magma-100" returns error:

```
pip install pytorch magma-cuda100
Collecting pytorch
  Using cached pytorch-1.0.2.tar.gz (689 bytes)
ERROR: Could not find a version that satisfies the requirement magma-cuda100 (from versions: none)
ERROR: No matching distribution found for magma-cuda100
WARNING: You are using pip version 20.2.4; however, version 21.0.1 is available.
You should consider upgrading via the '/home/richard/improbable/venvs/exp-runner/bin/python3 -m pip install --upgrade pip' command.

```

**Comment by bamdevm** [comment]
Yes, we should think about that. We are aware of the issue nevertheless.

By the way, did you observe the speed up, ie, GPU utilization for your problem?

**Comment by richardrl** [comment]
@bamdevm I am still trying I will update soon

**Comment by bamdevm** [comment]
Thanks @richardrl, looking forward to your feedback.
